#!/bin/bash

# directory sort
# GNU Affero General Public License v3.0

eco() { echo -e "\n\n"; }
directory=~/Downloads

main() {
	clear
	cd $directory
	eco
	ls
	eco
	for item in *;
	do 
		if [[ "$item" = *.png ]]; 
		then
			mv -v $item photos;
		elif [[ "$item" = *.jpg ]]; 
		then
			mv -v $item photos;
		elif [[ "$item" = *.pdf ]];
		then
			mv -v $item pdf;
		elif [[ "$item" = *.zip ]];
		then 
			mv -v $item zip;
		elif [[ "$item" = *.mp3 ]];
		then
			mv -v $item mp3;
		elif [[ "$item" = *.wav ]];
		then
			mv -v $item wav;
		fi;
	done
	ls;
}

main
